### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kukosek** [mcserverhosting-net/charts#39]
Hello, I would like to host minecraft in kubernetes. I dont really understand what this does. Also, it would be good to make a web panel with console? But i don't really know how to do that, since you cant ssh to the container lmao

**Comment by sfxworks** [comment]
Hi there.

These are what are known as helm charts. Helm charts are a collection of templates for applying kubernetes manifests. For more information on helm, check out https://helm.sh/

A lot of our charts are meant to be more native rather that working with traditional methods such as ssh. For example, console access is done using `kubectl attach`. You're more than welcome to contribute a web console! Though we are a CLI based host so we do not use one. You're free to look at other web GUI tools for kubernetes and helm such as the "Kubernetes Dashboard" or "Argocd". These and other charts are compatible with them. 

We will not be documenting these further though. Our readme lists parameters available. We may add a bit of context for new users getting started with kubernetes.

**Comment by kukosek** [comment]
Thanks very much, I didn't knew about the attach command! That will make things easy.

**Comment by sfxworks** [comment]
FYI continuing work on this this week. Work has had me busy so I apologize.
